### ISSUE TITLE
例子运行不起来

### ISSUE THREAD

**Issue by DexSinis** [southpeak/Minya#3]
# pragma mark - KVO
- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary<NSKeyValueChangeKey,id> *)change context:(void *)context {
  
  __MIKVOInfo *info = (__bridge __MIKVOInfo *)(context);
  if (info.changed) {
      id newValue = [change valueForKey:NSKeyValueChangeNewKey];
      info.changed([newValue isKindOfClass:[NSNull class]] ? nil : newValue);
  }
  }

报错no type protocol name 'NSKeyValueChangeKey'
是我步骤有问题么
xcode 7.3.1

**Comment by southpeak** [comment]
在xcode 7上不支持NSKeyValueChangeKey，现在已经去掉了
