### ISSUE TITLE
MVVM的网络请求有必要单独放到一个service类中吗？

### ISSUE THREAD

**Issue by Huang-Libo** [southpeak/Minya#4]
看了你画的mvcs图，非常棒！现在我有一个疑问，网络请求在MVVM中的标准位置是哪里？是直接放到view model中还是单写一个service类中？

**Comment by southpeak** [comment]
> 是直接放到view model中还是单写一个service类中？

嗯，我们的网络请求单独放在一个service里面的考虑有这么几点：
1. service可以重用
2. store所需要的只是数据，它从service里面取数据就行，而不关心service怎么取，不关心网络层是怎么实现的
3. 如果需要替换网络实现，只需要修改service层的代码，而不关乎上层的处理

您可以根据自己的实际需求，去确定网络请求是放在view model里面还是独立一个service来处理

**Comment by btxkenshin** [comment]
好像跟MVVM差别不是很大吧，顺便问下，这个MVCS图是什么工具制作的

**Comment by southpeak** [comment]
> 好像跟MVVM差别不是很大吧，顺便问下，这个MVCS图是什么工具制作的

嗯，MVVM，MVCS出发点都是轻量化view controller~~图是用keynote画的
